---
openapi: 3.1.0
info:
  title: Europeana Media Proxy
  summary: Micro-service to proxy media from providers.
  version: 0.0.1
components:
  parameters:
    datasetId:
      name: datasetId
      in: path
      description: Dataset ID of item
      required: true
      schema:
        type: integer
      examples:
        oorlogsvlijt-example:
          summary: '"Oorlogsvlijt in Harderwijk." item dataset ID'
          value: 2020601
    localId:
      name: localId
      in: path
      description: Local ID of item
      required: true
      schema:
        type: string
      examples:
        oorlogsvlijt-example:
          summary: '"Oorlogsvlijt in Harderwijk." item local ID'
          value: https___1914_1918_europeana_eu_contributions_14524
    webResourceHash:
      name: webResourceHash
      in: path
      description: MD5 hash of web resource URL
      required: true
      schema:
        type: string
      examples:
        oorlogsvlijt-example:
          summary: '"Oorlogsvlijt in Harderwijk." item web resource hash'
          description: MD5 hash of URL `https://europeana1914-1918.s3.amazonaws.com/attachments/152075/14524.152075.original.jpg`
          value: 304028f2553becc2bb0e4c0164439ec8

paths:
  /:
    get:
      summary: Root (health check)
      operationId: getRootHealthCheck
      responses:
        '200':
          description: OK if app is healthy
          content:
            text/plain:
              schema:
                type: string
  /media/{datasetId}/{localId}:
    parameters:
    - $ref: '#/components/parameters/datasetId'
    - $ref: '#/components/parameters/localId'
    get:
      summary: Redirect to proxy media for edm:isShownBy
      operationId: getRedirectEdmIsShownBy
      responses:
        '302':
          description: Redirect to getProxyWebResource for edm:isShownBy
          headers:
            location:
              description: URL to proxy edm:isShownBy of the item
              schema:
                type: string
          content:
            '*/*':
              schema:
                type: string
        '404':
          description: Item not found, or has no edm:isShownBy
          content:
            text/plain:
              schema:
                type: string
  /media/{datasetId}/{localId}/{webResourceHash}:
    parameters:
    - $ref: '#/components/parameters/datasetId'
    - $ref: '#/components/parameters/localId'
    - $ref: '#/components/parameters/webResourceHash'
    - $ref: '#/components/headers/acceptAllHeader'
    get:
      summary: Proxy media for specific web resource
      operationId: getProxyWebResource
      responses:
        '200':
          description: Media proxied
          headers:
            x-europeana-web-resource:
              description: URL of proxied web resource
              schema:
                type: string
                example: https://europeana1914-1918.s3.amazonaws.com/attachments/152075/14524.152075.original.jpg
          content:
            '*/*':
              schema:
                type: string
                format: binary
              examples:
                oorlogsvlijt:
                  $ref: '#/components/examples/oorlogsvlijt-example'
        '404':
          description: Item not found, or has no such web resource
          content:
            text/plain:
              schema:
                type: string
servers:
- url: https://media-proxy-js.test.eanadev.org
  description: Test server
- url: http://localhost:3000
  description: Local development server
